### ISSUE TITLE
Generating tags

### ISSUE THREAD

**Issue by icereed** [icereed/paperless-gpt#1]
While we have initial support for tags, the user experience is not really nice. Next step is to enhance the selection of tags, and also maybe to introduce a tags-only mode, if you're already happy with your titles.

**Comment by mikekaldig** [comment]
Hey, when do you think you'll implement the tags? I saw in my version that the fields are already set up in the web interface, but no tags are being generated yet. I'm currently setting up Paperless and exploring the possibilities of using AI for tags and headings. I would prefer not to switch plugins again.

**Comment by icereed** [comment]
Hey @mikekaldig, in theory it should work right now with tags being suggested as a comma-separated text field. For the prompt paperless GPT queries paperless-ngx first to see which tags are available at all.
Have you defined tags? If yes, which LLM are you using?

If I wouldn’t limit the LLMs to choose from an existing tag set, they would constantly add new ones.

**Comment by icereed** [comment]
This feature is pushed to icereed/paperless-gpt:latest

**Comment by mikekaldig** [comment]
Ty :)
