### ISSUE TITLE
Disable auto tagging

### ISSUE THREAD

**Issue by dawidkulpa** [icereed/paperless-gpt#10]
Brilliant work on the project guys! However, the lack of ability to disable applying tag suggestions makes me unable to use this project :( 
Generating titles works well, but suggested tags mess up my already properly set tags. 
IMO, there should be an option to just not apply them, either by setting it by ENV, or somewhere on the UI. 

Also, for a few larger docs, it generated a title of 1500+ characters :D Maybe some double checking if the model didn't go too far with it, and invalidating those results? 

I made it analyze 50 docs at once, and with these issues, it could also be helpful being able to pick ones you want to apply, or just remove the ones you don't like :)

What do you guys think about all this? I could open some PRs with changes, but I'd like to know first if you agree with these points :)

**Comment by icereed** [comment]
Thanks for this suggestion! Yes, I was thinking of something like this already.
I like the idea. Originally, paperless-gpt was titles only. A few commits back is only titles 😁

If you want to try a PR, I'm more than happy to support. 😊

**Comment by icereed** [comment]
Hey @dawidkulpa, I tried to incorporate your idea into a redesign I wanted to do: https://github.com/icereed/paperless-gpt/pull/11

Can you give that a try?
Do you need a docker tag for that?

**Comment by dawidkulpa** [comment]
Oh, cool! No need for docker tag just yet, I have the repo checked out anyways, so I'll just pull the changes. and run a dev build.
I'll let you know soon :)

**Comment by icereed** [comment]
This feature is implemented and merged on the main branch.
Until the new release is published, this feature can be used with `icereed/paperless-gpt:unreleased`.
