### ISSUE TITLE
Missing Contributing Guidelines File

### ISSUE THREAD

**Issue by peta999** [icereed/paperless-gpt#18]
### Issue: Missing Contributing Guidelines File

**Description:**

The repository mentions contributing guidelines in the README file, but the linked contributing file (`CONTRIBUTING.md`) does not exist.

**Steps to Reproduce:**
1. Navigate to the README file.
2. Click on the link for the contributing guidelines.
3. Notice the 404 error or missing page.

**Expected Behavior:**
The contributing file should exist and provide clear instructions for contributing guidelines.

**Suggested Solution:**
- Add a `CONTRIBUTING.md` file with detailed instructions.
- Ensure the link in the README points to the correct file.

**Comment by icereed** [comment]
Thank you, dome :)
