### ISSUE TITLE
Prompts folder could not be accessed but is mounted

### ISSUE THREAD

**Issue by stehol82** [icereed/paperless-gpt#27]
By starting the container I got the error: Could not read prompts/title_prompt.tmpl, using default template: open prompts/title_prompt.tmpl: no such file or directory

I assume that this file should be created when not existing.

But ./prompts is mounted and also shown as mounted in the docker settings. Rights are also doublechecked. 

My Settings in docker compose file:
    volumes:
      - ./prompts:/app/prompts

Any idea why the prompts folder could not be accessed?

**Comment by icereed** [comment]
Hi, does it work without the mount? If yes, which operating system do you use?

**Comment by leimer** [comment]
Try using the absolute path like `/volume1/docker/paperless-gpt/prompts:/app/prompts`.
Also double check the container has the correct user setting, to access the folder.

**Comment by stehol82** [comment]
Hi, already tried to use absolute path. The User has admin rights, so should also be able to access the folder (same folder than the docker-compose file, which can also be accessed without issues). BR

**Comment by stepanov1975** [comment]
I have the same issue. I use absolute path and directory is mounted. I checked it by creating file from inside container and it was created on host. Seems like files just not copied on container start.

**Comment by icereed** [comment]
I found the issue and the fix: https://github.com/icereed/paperless-gpt/pull/30

**Comment by icereed** [comment]
The release is published. Can you please retry by doing `docker compose pull` and `docker compose up -d`?

**Comment by stehol82** [comment]
Yes. Thx. Works now perfectly
