### ISSUE TITLE
Documents with paperless-gpt tag not discovered

### ISSUE THREAD

**Issue by stepanov1975** [icereed/paperless-gpt#35]
I added a paperless-gpt tag to multiple documents. Some of them appear in GUI, and some of them do not. Currently, I have a couple of documents that do not appear in the GUI
![image](https://github.com/user-attachments/assets/88e59ff1-fd07-4d83-90d8-b5ed721ed25f)

![image](https://github.com/user-attachments/assets/7dfb7d38-7738-41c0-8d84-279782cc18db)

**Comment by icereed** [comment]
That’s weird. Paperless-gpt asks the API to give all documents with that tag. By any chance, is there a duplicate tag with the name `paperless-gpt`?

**Comment by stepanov1975** [comment]
no
![image](https://github.com/user-attachments/assets/d01ad1f9-2353-4221-83de-3ce40d334c8c)

**Comment by icereed** [comment]
Interesting, before we check the API output, do you see anything related in the logs?

**Comment by stepanov1975** [comment]
Don't see anything interesting
[paperless-gpt-2024-10-26T15-57-09.log](https://github.com/user-attachments/files/17531201/paperless-gpt-2024-10-26T15-57-
09.log)

**Comment by icereed** [comment]
Can you check what the paperless-ngx API returns using cURL and output the response?

```sh
curl -X GET "http://localhost:8000/api/documents/?query=tag:paperless-gpt" -H "Content-Type: application/json" -H "Authorization: Token your-paperless-token"
```

Please adjust this command to use the right host, port and token.
Once I know the output, I can track down the issue in the code.

**Comment by stepanov1975** [comment]
There is a mess with tags. If I run this as admin, it shows the tag, but I created a separate user for paperless gpt and this user can see other tags but not paperless-gpt tag. I deleted this tag during my experiment and now paperless GUI shows zero documents with paperless-gpt tag but curl request shows to documents. I will need to open bug in paperless-ngx git :(

**Comment by icereed** [comment]
Interesting 🤔 I wasn’t aware of tags being owner dependent. Good to know 👍

**Comment by icereed** [comment]
Do you think there is something that we can do for paperless-gpt to work around this issue or at least provide better guidance to users?

**Comment by icereed** [comment]
Closing this for the time being
