### ISSUE TITLE
Suggestions for Enhancement: Tag Selection, Individual Tagging, Version Display, and Popup Design

### ISSUE THREAD

**Issue by mikekaldig** [icereed/paperless-gpt#36]
Hey, first of all, thanks for your quick adjustments. This makes the extension very usable for all of us. :)

I noticed that not all tags are available in the selection. It seems that not all of them are being retrieved. For example, I have "New Document" as a tag, but it’s not available in the selection. I also think it would make sense to allow tagging of documents individually, as another user had already suggested.

Additionally, it would be great to have a version number displayed in the web interface. Lastly, one more request: it's great that you can preview the document in a popup, but I’d prefer a style similar to the one in Paperless itself—perhaps even the styling from Paperless directly. Please see the image.

Thanks for your effort!
![Screenshot 2024-10-27 194818](https://github.com/user-attachments/assets/5915c2f6-ba81-495f-b71a-46a14802625d)

**Comment by icereed** [comment]
Hi @mikekaldig, you’re welcome ☺️ there was an issue with tags two versions ago. Did you pull the latest version? Regarding the styling, I’ll have a look. 🙂

**Comment by mikekaldig** [comment]
I downloaded the latest version. Or do I need to update with a specific version?

`version: '3.8'
services:

  paperless-gpt:
    image: icereed/paperless-gpt:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PAPERLESS_BASE_URL: 'http://10.10.10.xxx:8777'
      PAPERLESS_API_TOKEN: 'xxx'
      LLM_PROVIDER: 'openai' # or 'ollama'
      LLM_MODEL: 'gpt-4o-mini'     # or 'llama2'
      OPENAI_API_KEY: 'xxx' # Required if using OpenAI
      LLM_LANGUAGE: 'German' # Optional, default is 'English'
      #OLLAMA_HOST: http://10.10.10.xxx:11434 # Useful if using Ollama
    ports:
      - '8080:8080'
#    depends_on:
#      - webserver
    volumes:
#      - /share/Container/paperlessgpt:/
      - ./prompts:/app/prompts # Mount the prompts directory`
      
 Not all tags are still being loaded. In Paperless, there is a tag called "New Document," but not all tags are being retrieved in Paperless-GPT.

![Screenshot 2024-10-27 200743_1](https://github.com/user-attachments/assets/9d3f0daf-0c41-4bf3-9238-a702fcc77d40)
![Screenshot 2024-10-27 201244_2](https://github.com/user-attachments/assets/56dc9d58-45e3-4a5a-9962-e331f1ac7553)
![Screenshot 2024-10-27 201333_3](https://github.com/user-attachments/assets/7db93f3e-2f1e-4eb6-95a9-268e0155d75a)

**Comment by icereed** [comment]
Thanks for the detailed analysis. I’m sure I can find the issue. Is it only happening for tags with spaces?

**Comment by mikekaldig** [comment]
It seems so.

**Comment by icereed** [comment]
Sorry to ask again, but did you try to run `docker compose pull` and then  `docker compose up -d` again?
There used to be an issue with tags, but that should be fixed. Just wondering.

**Comment by mikekaldig** [comment]
yeah, i delete the image too.

docker ps 
docker stop Container-ID
docker images
docker rmi Image-ID
docker-compose pull
docker-compose up --build

right or?

**Comment by icereed** [comment]
Ah, actually, you can skip the —-build. `—-build` means the image will be built from the git repository that you cloned. Maybe that’s old.

If you prefer to build on your machine you can keep using —-build, but then need to do `git pull` first.

**Comment by mikekaldig** [comment]
This fixed my issue :)

Thanks
![Screenshot 2024-10-28 204616_11](https://github.com/user-attachments/assets/d591adf4-0fa4-41d6-b734-963c9e3af58d)

**Comment by icereed** [comment]
Perfect 👌
